
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import AnimatedBg from "./component/animatedbackground";

const fontMain = Poppins({
  variable: "--poppins",
  subsets: ["devanagari", "latin", "latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontMain.variable} ${fontMain.variable} antialiased font-main bg-gradient-to-bl from-black  to-teal-950`}
      >
        <AnimatedBg />
        
     {children}
      </body>
    </html>
  );
}
